name: Michael Lanyon's Blog
url: 'https://blog.lanyonm.org'
description: 'Notes and thoughts from LanyonM'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Michael Lanyon'
disqus_shortname: lanyonm
google_analytics: G-NN7JP65RMS

gems:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
